[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
outcry = "D2rYtfu8x3CxJ89YoAUrWbfiMGhFbAtE9Hq8RNoJaUZt"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/uFp3rRJkzmqosOBGtDM6cYysYH0WmufN"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/program/smoke.test.mjs"
