import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("./PitOverlay.tsx", import.meta.url), "utf8");
const intentSource = await readFile(new URL("../match/TradeIntentPanel.tsx", import.meta.url), "utf8");
assert.doesNotMatch(source, /setError\([^\n]+\);\s*onExit\(\);/);
assert.match(source, /Retry wallet join/);
assert.match(source, />Leave seat<\/button>/);
assert.match(source, /matchSnapshot\?\.taker === walletAddress/);
assert.match(source, /Media is unavailable; match state remains available/);
assert.match(source, /Reconnect media/);
assert.match(source, /VITE_SOLANA_BASE_RPC/);
assert.doesNotMatch(source, /VITE_SOLANA_RPC|NEXT_PUBLIC_SOLANA_RPC/);
assert.match(source, /insufficient Devnet SOL/);
assert.match(source, /already joined in a different seat/);
assert.match(source, /bootstrapMatchOnchain/);
assert.match(source, /match_account_not_initialized/);
assert.match(source, /onChainSeatConflict/);
assert.match(source, /Restoring that seat/);
assert.match(intentSource, /!draft \|\| !confirmed \|\| !onSubmit/);
console.log("pit overlay: first seated wallet lazily bootstraps a missing Match after simulation, then joins");
