import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("./PitOverlay.tsx", import.meta.url), "utf8");
const intentSource = await readFile(new URL("../match/TradeIntentPanel.tsx", import.meta.url), "utf8");
assert.doesNotMatch(source, /setError\([^\n]+\);\s*onExit\(\);/);
assert.match(source, /Retry wallet join/);
assert.match(source, />Leave seat<\/button>/);
assert.match(source, /currentRoundTaker/);
assert.match(source, /roundStatus === "PREPARED"/);
assert.match(source, /matchReadInFlightRef/);
assert.match(source, /autoStartAttemptedRef/);
assert.match(source, /media connected/);
assert.match(source, /onRetry=\{\(\) => setMatchRevision/);
assert.match(source, /role={role}/);
assert.match(source, /Media is unavailable; match state remains available/);
assert.match(source, /Reconnect media/);
assert.match(source, /browserBaseRpc/);
assert.match(source, /requireBaseSolanaRpc/);
assert.match(source, /startMatchInFlightRef/);
assert.match(source, /selectedRoundCount/);
assert.match(source, /roundCount,/);
assert.match(source, /onRoundCountChange={setSelectedRoundCount}/);
assert.match(source, /WAITING_MATCH_POLL_MS = 15_000/);
assert.match(source, /ACTIVE_MATCH_POLL_MS = 10_000/);
assert.match(source, /RoomEvent\.DataReceived/);
assert.match(source, /publishData/);
assert.match(source, /RFQ_OPEN_TOPIC/);
assert.match(source, /isMatchStateNotification/);
assert.match(source, /round-resolved/);
assert.match(source, /visibilitychange/);
assert.match(source, /createBaseRpcConnection/);
assert.match(source, /loadRuntimeMatchState/);
assert.match(source, /teeMatchConnection/);
assert.match(source, /Live TEE state unavailable/);
assert.doesNotMatch(source, /setInterval\(refresh, 1_500\)/);
assert.doesNotMatch(source, /getAccountInfo\(new PublicKey\(matchAddress\)/);
assert.match(source, /VITE_MAGICBLOCK_TEE_RPC/);
assert.match(source, /baseRpcUrl: requireBaseSolanaRpc\(\)/);
assert.match(source, /teeRpcUrl: teeSolanaRpc/);
assert.match(source, /authorityAddress: takerAddress/);
assert.match(source, /\[outcry\]\[resolve_round\]/);
assert.match(source, /\[outcry\]\[skip_empty_round\]/);
assert.match(source, /skipEmptyRoundOnchain/);
assert.match(source, /resumeSkippedRoundOnchain/);
assert.match(source, /private inventory state is unavailable/);
assert.match(source, /permissionless_relayer_unreachable/);
assert.match(source, /round relayer could not be reached/);
assert.match(source, /separate TEE fee-payer key/);
assert.match(source, /TEE fee payer is not ready/);
assert.match(source, /relayer_simulation_failed/);
assert.match(source, /runtime route is not ready/);
assert.match(source, /tee_relayer_route_mismatch/);
assert.match(source, /private_state_route_mismatch/);
assert.match(source, /private quote or inventory accounts have not been delegated/);
assert.match(source, /failed during/);
assert.match(source, /relayer_confirmation_failed/);
assert.doesNotMatch(source, /VITE_SOLANA_RPC|NEXT_PUBLIC_SOLANA_RPC/);
assert.match(source, /insufficient Devnet SOL/);
assert.match(source, /HostCannotJoin\|Error Number:\\s\*6060/);
assert.match(source, /deployed Outcry program is outdated/);
assert.match(source, /bootstrapMatchOnchain/);
assert.match(source, /VITE_OUTCRY_MATCH_NONCE/);
assert.match(source, /nonce: currentMatchNonce/);
assert.match(source, /preferredMatchNonce: currentMatchNonce/);
assert.match(source, /active_v2_match_nonce_unrecoverable/);
assert.match(source, /match_account_not_initialized/);
assert.match(source, /not a current MatchV2 account/);
assert.match(source, /onChainSeatConflict/);
assert.match(source, /onWalletJoinStarted/);
assert.match(source, /awaiting_confirmation/);
assert.match(source, /MatchV2 is durable metadata/);
assert.doesNotMatch(source, /restoreDelegatedMatchOnchain/);
assert.doesNotMatch(source, /preparePrivateQuoteOnchain/);
assert.match(source, /matchOwnership !== "delegated"/);
assert.match(intentSource, /!draft \|\| !confirmed \|\| !onSubmit/);
console.log("pit overlay: first seated wallet lazily bootstraps a missing Match after simulation, then joins");
