import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("./WorldScene.ts", import.meta.url), "utf8");
assert.match(source, /this\.room\.input<WorldMoveInput>/);
assert.match(source, /this\.prediction\.tick\(time\)/);
assert.match(source, /this\.localReconciler = this\.prediction\.reconciler/);
assert.match(source, /applyMovement\(player, input, this\.collision!, context\.dtMs\)/);
assert.match(source, /if \(player\.mode === "RECONNECTING"\)/);
assert.match(source, /this\.remotePlayers\.delete\(sessionId\)/);
assert.match(source, /private sendRoomMessage\(type: string/);
assert.match(source, /onConnectionLost\?\.\(\)/);
assert.match(source, /chainConfirmed: value\.action === "confirmed" \|\| value\.action === "restored"/);
assert.match(source, /localState\?\.mode === "RESERVING"/);
assert.match(source, /onMessage\("chat"/);
assert.match(source, /CHAT_BUBBLE_DURATION_MS/);
assert.match(source, /fillPoints\(points, true\)/);
assert.match(source, /const PIT_ART_DISPLAY_SIZE = 200;/);
assert.match(source, /setDisplaySize\(PIT_ART_DISPLAY_SIZE, PIT_ART_DISPLAY_SIZE\)/);
assert.match(source, /new URLSearchParams\(globalThis\.location\?\.search\)\.has\("debugWorld"\)/);
assert.doesNotMatch(source, /if \(!this\.room\?\.state\.players\.has\(value\.sessionId\)\) return;/);
console.log("world scene: fixed-step input prediction, chat, and debug marker gating pass");
