import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile("programs/outcry/src/lib.rs", "utf8");
const devnetSetup = await readFile("tools/prepare-devnet-match-tx.mjs", "utf8");
const devnetConfig = await readFile("tools/devnet-config.mjs", "utf8");
const localnetRunner = await readFile("tools/test-program-localnet.mjs", "utf8");
assert.match(source, /declare_id!\("[1-9A-HJ-NP-Za-km-z]{32,44}"\)/);
assert.match(source, /pub fn initialize/);
assert.match(source, /pub fn initialize_pit/);
assert.match(source, /pub fn create_match/);
assert.match(source, /pub fn join_match/);
assert.match(source, /pub fn renew_session/);
assert.match(source, /SESSION_MAX_DURATION_SECONDS: i64 = 24 \* 60 \* 60/);
assert.match(source, /pub struct MatchV2/);
assert.doesNotMatch(source, /pub seats:/);
assert.doesNotMatch(source, /seat_index/);
assert.match(source, /pub fn start_match/);
assert.match(source, /pub fn initialize_match_result/);
assert.match(source, /pub fn initialize_escrow/);
assert.match(source, /pub fn open_rfq\(/);
assert.match(source, /pub fn submit_quote\(/);
assert.match(source, /pub fn resolve_round\(/);
assert.match(source, /pub fn skip_empty_round/);
assert.match(source, /pub fn advance_round/);
assert.match(source, /pub fn finalize_runtime/);
assert.match(source, /pub fn finalize_match/);
assert.match(source, /pub fn settle_match/);
assert.match(source, /pub struct MatchRuntime/);
assert.match(source, /seeds = \[MATCH_SEED/);
assert.match(source, /const MATCH_SEED: &\[u8\] = b"match_v2"/);
assert.match(source, /PRIVATE_QUOTE_SEED, match_state\.key\(\)\.as_ref\(\), authority\.key\(\)\.as_ref\(\)/);
assert.match(source, /seeds = \[b"result"/);
assert.match(localnetRunner, /OUTCRY_BUILD_FEATURES: "localnet"/);
assert.match(localnetRunner, /copyFile\(backupSo, programSo\)/);
assert.match(devnetSetup, /UNSIGNED_ONLY/);
assert.match(devnetSetup, /initialize_pit/);
assert.match(devnetSetup, /create_match/);
assert.match(devnetSetup, /join_match/);
assert.match(devnetSetup, /match_v2/);
assert.match(devnetSetup, /runtime/);
assert.match(devnetSetup, /sigVerify: false/);
assert.match(devnetSetup, /replaceRecentBlockhash: true/);
assert.match(devnetConfig, /MAGICBLOCK_PYTH_ORACLE_PROGRAM_ID/);
assert.match(devnetConfig, /readMagicblockPythPreflight/);
assert.match(devnetConfig, /resolveBaseRpcUrl/);
console.log("program smoke: Anchor entrypoint, Phase 5/7 instructions, session paths, PDAs, retry-safe localnet harness, unsigned base-layer bootstrap plan, RPC/Pyth helpers, and program ID present");
