import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile("programs/outcry/src/lib.rs", "utf8");
const localnetHarness = await readFile("tools/phase-07.localnet.mjs", "utf8");
const devnetSetup = await readFile("tools/prepare-devnet-match-tx.mjs", "utf8");
const devnetConfig = await readFile("tools/devnet-config.mjs", "utf8");
const localnetRunner = await readFile("tools/test-program-localnet.mjs", "utf8");
assert.match(source, /declare_id!\("[1-9A-HJ-NP-Za-km-z]{32,44}"\)/);
assert.match(source, /pub fn initialize/);
assert.match(source, /pub fn initialize_pit/);
assert.match(source, /pub fn create_match/);
assert.match(source, /pub fn join_match/);
assert.match(source, /pub fn start_match/);
assert.match(source, /pub fn initialize_match_result/);
assert.match(source, /pub fn initialize_escrow/);
assert.match(source, /pub fn open_rfq_session/);
assert.match(source, /pub fn submit_quote_session/);
assert.match(source, /pub fn resolve_round_session/);
assert.match(source, /pub fn next_round_session/);
assert.match(source, /pub fn settle_match/);
assert.match(source, /seeds = \[b"match"/);
assert.match(source, /seeds = \[b"result"/);
assert.match(localnetHarness, /const SUBMIT_ATTEMPTS = 4/);
assert.match(localnetHarness, /async function simulateExpectedFailure/);
assert.match(localnetHarness, /const QUOTE_WINDOW_SECONDS = 30/);
assert.match(localnetRunner, /OUTCRY_BUILD_FEATURES: "localnet"/);
assert.match(localnetRunner, /copyFile\(backupSo, programSo\)/);
assert.match(localnetHarness, /const PYTH_PUBLISH_TIME_OFFSET = 93/);
assert.match(localnetHarness, /error\.getLogs\(connection\)/);
assert.match(devnetSetup, /UNSIGNED_ONLY/);
assert.match(devnetSetup, /initialize_pit/);
assert.match(devnetSetup, /create_match/);
assert.match(devnetSetup, /sigVerify: false/);
assert.match(devnetSetup, /replaceRecentBlockhash: true/);
assert.doesNotMatch(devnetSetup, /initialize_oracle|initialize_match_result|initialize_escrow|join_match/);
assert.match(devnetConfig, /MAGICBLOCK_PYTH_ORACLE_PROGRAM_ID/);
assert.match(devnetConfig, /readMagicblockPythPreflight/);
assert.match(devnetConfig, /resolveBaseRpcUrl/);
console.log("program smoke: Anchor entrypoint, Phase 5/7 instructions, session paths, PDAs, retry-safe localnet harness, unsigned base-layer bootstrap plan, RPC/Pyth helpers, and program ID present");
